version: '3.4'

services:

  referencedb:
    container_name: referencedb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  pgsysintegrator.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IntegratorConnectionString=Server=referencedb;Database=ReferenceDb;User Id=sa;Password=SwN12345678"   
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - referencedb
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro